# Exception 抛出异常

Yao 内部集成了`Exception`可以在任意 JS 文件中抛出异常，终止程序运行

## 示例

Exception 抛出异常：

```javascript
throw new Exception("页面未找到", 404);
```

<Div style={{ display: "flex", justifyContent: "space-between" }}>
  <Link type="prev" title="Log" link="手册/JSAPI/Log"></Link>
  <Link type="next" title="Query" link="手册/JSAPI/Query"></Link>
</Div>
